# Generated by Django 5.1.5 on 2025-01-30 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_prof_manager_app', '0002_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('goals', models.TextField(blank=True, max_length=300, null=True)),
                ('motivations', models.TextField(blank=True, max_length=300, null=True)),
                ('concerns', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
